FROM tensorflow/tensorflow:1.15.2-gpu-py3
RUN apt-get update -y && apt install build-essential \
cmake \
vim \
libglib2.0-0 \
libsm6 \
libxrender1 \
libxext6 \
libfontconfig1 -y

COPY . /age-gender-estimation
WORKDIR /age-gender-estimation
EXPOSE 8080
ENV GPU=true
ENV GPU_FRACTION=0.25
RUN pip3 install -r requirements-gpu.txt
CMD ["python3", "api.py"]
